#!/usr/bin/env python3
"""Regenerate the DeepSeek Harness OpenSpec skills under .dsh/skills/.

`openspec init` / `openspec update` write skill bundles only for the tools in the
OpenSpec CLI's own AI_TOOLS registry, and DeepSeek Harness is not one of them.
DSH does discover project skills from `.dsh/skills/<name>/SKILL.md`, so this
script re-derives that root from the `.zcode` bundle the CLI does maintain. One
`openspec update` followed by this script keeps both tools current.

The upstream skill body is copied verbatim apart from the adaptations listed in
REWRITES below; descriptions, step order, CLI calls and guardrails all stay as
the CLI generated them.

Usage:
    python3 scripts/sync-dsh-skills.py [repo-root]
    python3 scripts/sync-dsh-skills.py --check [repo-root]

`--check` writes nothing and exits 1 when a generated file is missing, stale, or
when the rewrite rules no longer match the source bundle.
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

SOURCE_REL = Path(".zcode") / "skills"
DEST_REL = Path(".dsh") / "skills"

# Adaptations applied to every generated body: (source text, replacement,
# expected occurrences across the whole run). The expected counts turn upstream
# template drift into a loud failure instead of a half-adapted skill.
REWRITES = (
    # DSH's tool for the same interaction.
    ("AskUserQuestion tool", "`ask_user_question` tool", 6),
    ("TodoWrite tool", "`todo_write` tool", 1),
    # DSH exposes a user-invocable skill as `/name`, and its composer rejects the
    # colon in the upstream `/opsx:<id>` form, so that spelling would arrive as
    # plain text instead of running the workflow.
    ("/opsx:apply", "/openspec-apply-change", 3),
    ("/opsx:explore", "/openspec-explore", 1),
    # DSH has no Claude-style Agent/Task tool carrying a `subagent_type`; its
    # subagent tool takes a self-contained prompt instead.
    (
        'use the Agent tool (subagent_type: "general-purpose", prompt: '
        '"Use Skill tool to invoke openspec-sync-specs for change \'<name>\'. '
        'Delta spec analysis: <include the analyzed delta spec summary>").',
        "delegate with the `subagent` tool, whose prompt loads the "
        "`openspec-sync-specs` skill for change '<name>' and carries the "
        "analyzed delta spec summary.",
        1,
    ),
)

GENERATED_PREFIX = "openspec-"

MARKER = (
    "<!-- Generated by scripts/sync-dsh-skills.py from "
    ".zcode/skills/{name}/SKILL.md -- edit that source, then re-run the script. -->"
)


def fail(message: str) -> None:
    print(f"sync-dsh-skills: {message}", file=sys.stderr)
    raise SystemExit(1)


def stamp(body: str, name: str) -> str:
    """Insert the provenance marker directly after the YAML frontmatter."""
    end = body.find("\n---\n", 3)
    if end == -1:
        fail(f"{name}: no closing YAML frontmatter delimiter found")
    insert_at = end + len("\n---\n")
    return f"{body[:insert_at]}\n{MARKER.format(name=name)}\n{body[insert_at:]}"


def generate(source: Path) -> dict[str, str]:
    """Read every source bundle and return the adapted SKILL.md contents."""
    names = sorted(p.name for p in source.iterdir() if (p / "SKILL.md").is_file())
    if not names:
        fail(f"no <skill>/SKILL.md bundles under {source}; run `openspec update` first")

    counts = {old: 0 for old, _, _ in REWRITES}
    generated: dict[str, str] = {}
    for name in names:
        text = (source / name / "SKILL.md").read_text(encoding="utf-8")
        for old, new, _ in REWRITES:
            counts[old] += text.count(old)
            text = text.replace(old, new)
        generated[name] = stamp(text, name)

    drift = [
        f"{old!r}: matched {counts[old]}x, expected {expected}x"
        for old, _, expected in REWRITES
        if counts[old] != expected
    ]
    if drift:
        fail(
            f"{source} no longer matches the rewrite rules -- upstream changed the "
            "skill templates; review them and update REWRITES:\n  " + "\n  ".join(drift)
        )
    return generated


def main(argv: list[str]) -> int:
    if {"-h", "--help"} & set(argv):
        print(__doc__.strip())
        return 0
    check = "--check" in argv
    positional = [a for a in argv if a != "--check"]
    unknown = [a for a in positional if a.startswith("-")]
    if unknown:
        fail(f"unknown option(s): {' '.join(unknown)} (try --help)")
    if len(positional) > 1:
        fail(f"expected at most one repo root, got {len(positional)}")
    root = Path(positional[0]).resolve() if positional else Path(__file__).resolve().parent.parent
    source = root / SOURCE_REL
    dest = root / DEST_REL

    if not source.is_dir():
        fail(f"missing source bundle {source}; run `openspec update` first")

    generated = generate(source)

    stale = sorted(
        p.name
        for p in dest.iterdir()
        if p.is_dir() and p.name.startswith(GENERATED_PREFIX) and p.name not in generated
    ) if dest.is_dir() else []

    written, unchanged, problems = [], [], []
    for name, content in sorted(generated.items()):
        target = dest / name / "SKILL.md"
        current = target.read_text(encoding="utf-8") if target.is_file() else None
        if current == content:
            unchanged.append(name)
            continue
        if check:
            problems.append(f"{target.relative_to(root)} is {'missing' if current is None else 'stale'}")
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        written.append(name)

    for name in stale:
        target = dest / name
        if check:
            problems.append(f"{target.relative_to(root)} is no longer generated")
            continue
        shutil.rmtree(target)

    if check:
        if problems:
            fail("generated skills are out of date:\n  " + "\n  ".join(problems))
        print(f"sync-dsh-skills: {len(unchanged)} generated skill(s) up to date under {DEST_REL}")
        return 0

    if stale:
        print(f"sync-dsh-skills: removed stale {', '.join(stale)}")
    if written:
        print(f"sync-dsh-skills: wrote {len(written)} skill(s) to {DEST_REL}: {', '.join(written)}")
    if unchanged:
        print(f"sync-dsh-skills: unchanged {', '.join(unchanged)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
